export const QUOTATION_ENGINE_VERSION = '0.7.1';
export const QUOTATION_STAGE = 'export-integrity-hotfix';

function inferDocumentKind(name=''){const value=String(name||'').toLowerCase();return /成本|工料|cost|price[-_ ]?list|material/.test(value)?'cost_master_candidate':'quotation_candidate';}
function stableHash(input=''){let hash=2166136261;for(const ch of String(input||'')){hash^=ch.charCodeAt(0);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(36).padStart(7,'0');}
function createSourceFileId(fileMeta={}){return `quote-source-${stableHash([fileMeta.name,Number(fileMeta.size||0),Number(fileMeta.lastModified||0),fileMeta.type,fileMeta.extension].join('|'))}`;}
function stripQuote(v=''){return String(v||'').trim().replace(/^[「『"']+|[」』"']+$/g,'').replace(/[。！!；;]+$/,'').trim();}
function numeric(v){const n=Number(String(v||'').replace(/,/g,''));return Number.isFinite(n)?n:null;}
function suggestionId(){return `qa-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;}

export function createQuotationEngine(){
  return Object.freeze({
    version:QUOTATION_ENGINE_VERSION,stage:QUOTATION_STAGE,
    schemas:Object.freeze({costMaster:'draft-policy-ready',quotationProject:'multi-draft-foundation',quoteItem:'semantic-row-v2',costComponent:'planned',workbookAction:'quote-action-v2'}),
    capabilities:Object.freeze({parseQuotation:true,matchCost:true,calculate:true,mutateWorkbook:true,exportWorkbook:true,draftEnvelope:true,draftRegistry:true,draftReopen:true,inspectorSync:true,readCostMaster:true,costGatewayReadOnly:true,dragDropIntake:true,manualCellEdit:true,aiCellSuggestions:true,chatWorkbookCommands:true,chatWorkbookContext:true,acceptRejectDiff:true,compareView:true,issueNavigation:true,rowClassification:true,printAreaAware:true,formulaRuntime:true,losslessCellPatchExport:true,dirtyCellJournalExport:true,exportIntegrityGate:true,staleCalcChainReset:true,sharedFormulaExportGuard:true,viewportPreservation:true,enterTabCellNavigation:true,liveSplitterRender:true}),
    createDraftEnvelope(fileMeta={},accessRole='member'){
      const kind=inferDocumentKind(fileMeta.name);const createdAt=new Date().toISOString();const sourceFileId=createSourceFileId(fileMeta);return{id:`quote-draft-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,draftId:null,sourceFileId,quotationProjectId:null,kind,status:'draft',pendingChangeCount:0,createdAt,updatedAt:createdAt,file:{...fileMeta},sourceImmutable:true,costMasterPolicy:{compareDraftOnly:kind==='cost_master_candidate',canPublishCostMaster:['admin','owner'].includes(accessRole),publishCreatesNewVersion:true,overwritePreviousVersion:false},quotationPolicy:{workingCopyOnly:kind==='quotation_candidate',exportCreatesNewFile:true,overwriteOriginalFile:false}};
    },
    normalizeDraftEnvelope(draft={}){if(!draft||typeof draft!=='object')return null;if(!draft.draftId)draft.draftId=String(draft.id||'');if(!draft.id)draft.id=String(draft.draftId||'');return draft;},
    createSuggestion({sheet,address,oldValue,newValue,oldFormula='',formula='',reason='',source='ai',kind='cell-update',row=null,payload=null}={}){return{id:suggestionId(),sheet:String(sheet||''),address:String(address||'').toUpperCase(),oldValue,newValue,oldFormula:String(oldFormula||''),formula:String(formula||''),status:'pending',reason:String(reason||''),source,kind,row:Number.isInteger(row)?row:null,payload:payload&&typeof payload==='object'?payload:null,createdAt:new Date().toISOString()};},
    parseNavigationCommand(text){const raw=String(text||'').trim();if(!raw)return null;let m=raw.match(/(?:前往|跳到|帶我去|定位到|找到)\s*(?:(.+?)\s*)?([A-Z]{1,3}\d+)\b/i);if(m)return{handled:true,type:'cell',sheetHint:stripQuote(m[1]||''),address:m[2].toUpperCase()};if(/(?:下一個|下一筆).*?(?:問題|疑慮|錯誤)/.test(raw))return{handled:true,type:'issue-next'};if(/(?:上一個|上一筆).*?(?:問題|疑慮|錯誤)/.test(raw))return{handled:true,type:'issue-prev'};if(/(?:第一個|第一筆|開始).*?(?:問題|疑慮|錯誤)/.test(raw))return{handled:true,type:'issue-first'};return null;},
    parseChatEditCommand(text,model,workbook){
      if(!model?.structured||!workbook)return null;const raw=String(text||'').trim();if(!raw)return null;const sheet=workbook.getSheet(model,model.activeSheet);if(!sheet)return null;const schema=workbook.inferTableSchema(model,sheet.name,'customer');const suggestions=[];
      const add=(row,col,newValue,reason)=>{if(row<0||col==null)return;const address=workbook.columnAddress(model,col,row);const oldValue=workbook.getCell(model,sheet.name,address)?.value??'';suggestions.push(this.createSuggestion({sheet:sheet.name,address,oldValue,newValue,reason,source:'chat'}));};
      const resolveItem=(itemNo)=>{const matches=workbook.findItemRowMatches?.(model,sheet.name,itemNo)||[];if(matches.length<=1)return{row:matches[0]?.row??-1};const named=matches.filter(x=>x.section&&raw.includes(String(x.section).trim()));if(named.length===1)return{row:named[0].row};return{row:-1,ambiguous:true,matches};};
      const ambiguousReply=(itemNo,matches)=>({handled:true,suggestions:[],message:`「第 ${itemNo} 項」在目前明細中出現 ${matches.length} 次，為避免改錯工程，請指定工程分類（例如「木作工程第 ${itemNo} 項」）或直接指定儲存格位址。`});
      let m=raw.match(/第\s*(\d+)\s*(?:項|列|行).*?(?:名稱|項目(?:名稱)?|工程項目)\s*(?:改成|改為|改|變成|設為)\s*(.+)$/i);if(m){const hit=resolveItem(m[1]);if(hit.ambiguous)return ambiguousReply(m[1],hit.matches);add(hit.row,schema.columns.itemName,stripQuote(m[2]),`聊天指令：第 ${m[1]} 項名稱`);}
      m=raw.match(/第\s*(\d+)\s*(?:項|列|行).*?(?:單價|價格|售價)\s*(?:改成|改為|改|變成|設為)\s*\$?\s*([\d,.]+)/i);if(m){const hit=resolveItem(m[1]);if(hit.ambiguous)return ambiguousReply(m[1],hit.matches);add(hit.row,schema.columns.unitPrice,numeric(m[2]),`聊天指令：第 ${m[1]} 項單價`);}
      m=raw.match(/第\s*(\d+)\s*(?:項|列|行).*?(?:數量|qty)\s*(?:改成|改為|改|變成|設為)\s*([\d,.]+)/i);if(m){const hit=resolveItem(m[1]);if(hit.ambiguous)return ambiguousReply(m[1],hit.matches);add(hit.row,schema.columns.qty,numeric(m[2]),`聊天指令：第 ${m[1]} 項數量`);}
      m=raw.match(/(?:管理費|監造費).*?(?:改成|改為|設為|調整為|改)\s*([\d.]+)\s*%/i);if(m){const pct=numeric(m[1]);for(const row of workbook.classifyRows(model,sheet.name,'customer')){if(!/(管理費|監造費)/.test(String(row.itemName||'')))continue;const targetCol=schema.columns.unitPrice??schema.columns.amount;if(targetCol==null)break;const address=workbook.columnAddress(model,targetCol,row.row),cell=workbook.getCell(model,sheet.name,address),oldFormula=String(cell?.formula||'');if(oldFormula&&/(\d+(?:\.\d+)?)\s*%/.test(oldFormula)){const formula=oldFormula.replace(/(\d+(?:\.\d+)?)\s*%/,`${pct}%`);suggestions.push(this.createSuggestion({sheet:sheet.name,address,oldValue:cell?.value??'',newValue:cell?.value??'',oldFormula,formula,kind:'formula-update',reason:`聊天指令：${String(row.itemName||'管理費').trim()}調整為 ${pct}%`,source:'chat'}));}else add(row.row,targetCol,pct/100,`聊天指令：管理費 ${pct}%`);break;}}
      m=raw.match(/(?:把|將)\s*(?:([^!]+)!)?([A-Z]+\d+)\s*(?:改成|改為|設為|改)\s*(.+)$/i);if(m){const targetSheet=m[1]?workbook.getSheet(model,stripQuote(m[1])):sheet;const address=m[2].toUpperCase();if(targetSheet){const oldValue=workbook.getCell(model,targetSheet.name,address)?.value??'';let value=stripQuote(m[3]);const maybe=numeric(value);if(maybe!==null&&/^[$\d,\.\s]+$/.test(String(m[3])))value=maybe;suggestions.push(this.createSuggestion({sheet:targetSheet.name,address,oldValue,newValue:value,reason:`聊天指令：${targetSheet.displayName||targetSheet.name}!${address}`,source:'chat'}));}}
      m=raw.match(/(?:新增|增加)(?:一)?(?:列|行|項)(?:[:：]?\s*)(.+)$/i);if(m){const name=stripQuote(m[1]).replace(/[。！!]+$/,'').trim();if(name){const range=workbook.getViewRange(model,sheet.name,'customer');const row=(range?.e?.r??sheet.range.e.r)+1;const payload={};if(schema.columns.itemName!=null)payload[schema.columns.itemName]=name;if(schema.columns.itemNo!=null)payload[schema.columns.itemNo]=row-schema.headerRow;suggestions.push(this.createSuggestion({sheet:sheet.name,address:`ROW:${row+1}`,oldValue:'',newValue:name,reason:`聊天指令：新增「${name}」`,source:'chat',kind:'append-row',row,payload}));}}
      if(!suggestions.length)return null;return{handled:true,suggestions,message:`已在「${sheet.displayName||sheet.name}」建立 ${suggestions.length} 筆待確認修改。請在報價工作台逐筆採用或略過；公式欄位會由 Formula Runtime 連鎖重算。`};
    },
    health(){return{ok:true,version:QUOTATION_ENGINE_VERSION,stage:QUOTATION_STAGE};}
  });
}
