export const QUANTITY_WINDOW_VERSION='0.1.0';
const HANDLES=['t','b','l','r','tl','tr','bl','br'];
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function ensureHandles(root){if(!root||root.querySelector('[data-quantity-resize]'))return;for(const name of HANDLES){const el=document.createElement('div');el.className=`quantity-window-resize quantity-window-resize-${name}`;el.dataset.quantityResize=name;root.appendChild(el);}}
function defaultRect(context,{defaultWidth=980,defaultHeight=720}={}){const drawer=context?.getMountRoot?.();const r=drawer?.getBoundingClientRect?.();const vw=window.innerWidth,vh=window.innerHeight;const width=clamp(Math.max(Number(r?.width||0),defaultWidth),560,Math.max(560,vw-24));const height=clamp(Math.max(Number(r?.height||0),defaultHeight),460,Math.max(460,vh-24));let left=Number.isFinite(r?.left)?r.left:Math.max(12,(vw-width)/2);let top=Number.isFinite(r?.top)?r.top:Math.max(12,(vh-height)/2);if(left+width>vw-8)left=Math.max(8,vw-width-8);if(top+height>vh-8)top=Math.max(8,vh-height-8);return{left,top,width,height};}
export function attachQuantityWindow(root,header,context,options={}){if(!root)return{cleanup(){},reset(){}};root._quantityWindowCleanup?.();ensureHandles(root);const minW=Number(options.minWidth||560),minH=Number(options.minHeight||460);let mode='',handle='',sx=0,sy=0,sw=0,sh=0,sl=0,st=0,raf=0,pending=null;
const raise=()=>{const z=Number(window.__leavesQuantityZIndex||100400)+1;window.__leavesQuantityZIndex=z;root.style.zIndex=String(z);};
const apply=r=>{root.style.left=`${Math.round(r.left)}px`;root.style.top=`${Math.round(r.top)}px`;root.style.width=`${Math.round(r.width)}px`;root.style.height=`${Math.round(r.height)}px`;root.style.right='auto';root.style.bottom='auto';root.style.transform='none';};
const reset=()=>{if(window.innerWidth<=760){root.style.left='8px';root.style.top='8px';root.style.right='8px';root.style.bottom='8px';root.style.width='auto';root.style.height='auto';root.style.transform='none';return;}apply(defaultRect(context,options));};
const begin=(e,kind,h='')=>{if(window.innerWidth<=760)return;if(kind==='drag'&&e.target.closest('button,input,select,textarea,[contenteditable="true"]'))return;e.preventDefault();e.stopPropagation();raise();const r=root.getBoundingClientRect();mode=kind;handle=h;sx=e.clientX;sy=e.clientY;sw=r.width;sh=r.height;sl=r.left;st=r.top;root.classList.add('is-window-interacting');document.body.style.userSelect='none';};
const applyPointer=p=>{if(!mode||!p)return;const dx=p.clientX-sx,dy=p.clientY-sy,vw=window.innerWidth,vh=window.innerHeight;if(mode==='drag'){apply({left:clamp(sl+dx,4,Math.max(4,vw-sw-4)),top:clamp(st+dy,4,Math.max(4,vh-sh-4)),width:sw,height:sh});return;}let left=sl,top=st,width=sw,height=sh;if(handle.includes('r'))width=clamp(sw+dx,minW,vw-sl-4);if(handle.includes('b'))height=clamp(sh+dy,minH,vh-st-4);if(handle.includes('l')){const d=clamp(dx,-sl+4,sw-minW);left=sl+d;width=sw-d;}if(handle.includes('t')){const d=clamp(dy,-st+4,sh-minH);top=st+d;height=sh-d;}apply({left,top,width,height});};
const flush=()=>{raf=0;const p=pending;pending=null;applyPointer(p);};const move=e=>{if(!mode)return;pending={clientX:e.clientX,clientY:e.clientY};if(!raf)raf=requestAnimationFrame(flush);};const end=()=>{if(!mode)return;if(raf){cancelAnimationFrame(raf);raf=0;}if(pending)applyPointer(pending);pending=null;mode='';handle='';root.classList.remove('is-window-interacting');document.body.style.userSelect='';};
const resize=()=>{if(window.innerWidth<=760){reset();return;}const r=root.getBoundingClientRect();apply({left:clamp(r.left,4,Math.max(4,window.innerWidth-r.width-4)),top:clamp(r.top,4,Math.max(4,window.innerHeight-r.height-4)),width:Math.min(r.width,window.innerWidth-8),height:Math.min(r.height,window.innerHeight-8)});};
const down=()=>raise();root.addEventListener('pointerdown',down);header?.addEventListener('pointerdown',e=>begin(e,'drag'));root.querySelectorAll('[data-quantity-resize]').forEach(el=>el.addEventListener('pointerdown',e=>begin(e,'resize',el.dataset.quantityResize||'')));window.addEventListener('pointermove',move,{passive:true});window.addEventListener('pointerup',end);window.addEventListener('pointercancel',end);window.addEventListener('resize',resize);reset();raise();
const cleanup=()=>{if(raf)cancelAnimationFrame(raf);root.removeEventListener('pointerdown',down);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',end);window.removeEventListener('resize',resize);document.body.style.userSelect='';root._quantityWindowCleanup=null;};root._quantityWindowCleanup=cleanup;return{cleanup,reset,raise};}
